### ISSUE TITLE
App is broken: "The Picasa API is deprecated"

### ISSUE THREAD

**Issue by dlxmax** [Bostwickenator/STGUploader#18]
The app officially broke on January 15, 2019--it needs to be migrated to the Google Photos API.

In the interim, as per directions (https://developers.google.com/picasa-web/docs/3.0/deprecation#extension) you can make a small code revision to keep it going until March 15, 2019, by which point let's hope it's rolling with the Google Photos API.

Thanks for your work. I just got a RX100III last month and this app makes it so much better.

> [INFO] Resume org.bostwickenator.googlephotos.MainActivity
> [INFO] Response Code : 400
> [ERROR] java.io.FileNotFoundException: https://picasaweb.google.com/data/feed/api/user/default/albumid/default
> [INFO] Pause org.bostwickenator.googlephotos.MainActivity

**Comment by inakihn** [comment]
Thanks for the pointers to the interim, it would be great to have it working again.

I imagine the fix is something along `PicasawebClient.java` at line 66 to add `?deprecation-extension=true` to that url. As I am not able to test the modification I haven't created a PR, but it would be great to have it fixed temporarily before moving to Google Photos API.

Thanks to @Bostwickenator for creating such a wonderful app, made me love my hx90 a lot.

**Comment by Bostwickenator** [comment]
Apologies for letting it slip. I really should collect metrics so I know how many people are using this. I'll publish an update this evening CST

**Comment by Bostwickenator** [comment]
Please update to 1.6 for the fix @inakihn was of course correct in the remediation 👍

**Comment by dlxmax** [comment]
Will we soon be able to push v1.6 to our cameras with PMCA? I just tried and it sent v1.5.

**Comment by Bostwickenator** [comment]
That is an artifact of the Amazon CloudFront distribution caching. The new release metadata has gone live now. Please reply if it still doesn't work for you.
